"""
AI Tool Backend
- /api/chat        -> coding help / general questions (Gemini)
- /api/generate-ppt -> generates a real .pptx file from a topic
"""

import os
import json
import re
import uuid

from flask import Flask, request, jsonify, send_from_directory
from flask_cors import CORS
import google.generativeai as genai
from pptx import Presentation
from pptx.util import Inches, Pt

# ---------- CONFIG ----------
# Put your free Gemini API key here, or set it as an environment variable
# called GEMINI_API_KEY on your hosting platform (Render/Railway).
API_KEY = os.environ.get("GEMINI_API_KEY", "PASTE_YOUR_GEMINI_API_KEY_HERE")

genai.configure(api_key=API_KEY)
model = genai.GenerativeModel("gemini-2.0-flash")

app = Flask(__name__)
CORS(app)  # allow the mobile web page to call this backend

OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "generated_files")
os.makedirs(OUTPUT_DIR, exist_ok=True)


# ---------- CHAT / CODING HELP ----------
@app.route("/api/chat", methods=["POST"])
def chat():
    data = request.get_json(force=True)
    user_message = data.get("message", "")

    if not user_message:
        return jsonify({"error": "message is required"}), 400

    try:
        response = model.generate_content(user_message)
        return jsonify({"reply": response.text})
    except Exception as e:
        return jsonify({"error": str(e)}), 500


# ---------- PPT GENERATION ----------
def ask_gemini_for_slides(topic, num_slides=6):
    """Ask Gemini to return slide content as strict JSON."""
    prompt = f"""
Create content for a PowerPoint presentation on the topic: "{topic}".
Return ONLY valid JSON, no markdown, no backticks, no extra text.
Format exactly like this:

{{
  "title": "Presentation Title",
  "slides": [
    {{"heading": "Slide heading", "bullets": ["point 1", "point 2", "point 3"]}}
  ]
}}

Create {num_slides} slides. Keep bullets short (max 12 words each), 3-5 bullets per slide.
"""
    response = model.generate_content(prompt)
    text = response.text.strip()

    # Clean up if Gemini wraps it in ```json ... ```
    text = re.sub(r"^```(json)?", "", text.strip())
    text = re.sub(r"```$", "", text.strip())

    return json.loads(text)


def build_pptx(data, filepath):
    prs = Presentation()

    # Title slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    slide.shapes.title.text = data.get("title", "Presentation")
    if len(slide.placeholders) > 1:
        slide.placeholders[1].text = "Generated by AI Tool"

    # Content slides
    bullet_layout = prs.slide_layouts[1]
    for s in data.get("slides", []):
        slide = prs.slides.add_slide(bullet_layout)
        slide.shapes.title.text = s.get("heading", "")
        body = slide.placeholders[1].text_frame
        bullets = s.get("bullets", [])
        for i, b in enumerate(bullets):
            if i == 0:
                body.text = b
            else:
                p = body.add_paragraph()
                p.text = b
                p.level = 0

    prs.save(filepath)


@app.route("/api/generate-ppt", methods=["POST"])
def generate_ppt():
    data = request.get_json(force=True)
    topic = data.get("topic", "")
    num_slides = int(data.get("num_slides", 6))

    if not topic:
        return jsonify({"error": "topic is required"}), 400

    try:
        slide_data = ask_gemini_for_slides(topic, num_slides)

        filename = f"{uuid.uuid4().hex}.pptx"
        filepath = os.path.join(OUTPUT_DIR, filename)
        build_pptx(slide_data, filepath)

        return jsonify({
            "message": "PPT generated successfully",
            "download_url": f"/api/download/{filename}",
            "title": slide_data.get("title", topic)
        })
    except json.JSONDecodeError:
        return jsonify({"error": "AI response could not be parsed. Try again."}), 500
    except Exception as e:
        return jsonify({"error": str(e)}), 500


@app.route("/api/download/<filename>", methods=["GET"])
def download(filename):
    return send_from_directory(OUTPUT_DIR, filename, as_attachment=True)


@app.route("/", methods=["GET"])
def health():
    return jsonify({"status": "AI Tool backend is running"})


if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port, debug=True)
